### ISSUE TITLE
莫名发现一辆车

### ISSUE THREAD

**Issue by kinglisky** [deepred5/reimu#1]
![](https://i.loli.net/2018/03/01/5a97653eac54a.jpg)

![](https://i.loli.net/2018/03/01/5a97654e12cea.jpg)

![](https://i.loli.net/2018/03/01/5a9765538dfd8.jpg)

**Comment by deepred5** [comment]
@kinglisky 走，去幼儿园的车

**Comment by kinglisky** [comment]
@deepred5 现在在啥公司？

**Comment by deepred5** [comment]
@kinglisky 在深圳一家P2P公司搬砖
